# Generated by Django 5.2.5 on 2025-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.CharField(blank=True, default='+91', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
