# Generated by Django 5.2.5 on 2025-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_address_country_code_address_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
